
import java.awt.BasicStroke;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.color.ColorSpace;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ms Store
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginFrame() {
        initComponents();
        txtmail.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtpass.setBackground(new java.awt.Color(0, 0, 0, 1));
        SignUpRoundPanel.setLocation(975, -10);
        SignUpRoundPanel.setSize(0, 380);
        Egypt.setEnabled(false);
        Egypt.setEditable(false);
        AutoCompleteDecorator.decorate(governorate);
        SignUPbg.setVisible(false);
        forgetPassPanel.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        gender = new javax.swing.ButtonGroup();
        closeButton = new PanelRound();
        closeSymbol = new javax.swing.JLabel();
        SignUPbg = new javax.swing.JPanel();
        SignUpRoundPanel = new PanelRound();
        signUp_w = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        suP = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        suE = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        female = new RadioButtonCustom();
        male = new RadioButtonCustom();
        jLabel17 = new javax.swing.JLabel();
        Egypt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        governorate = new javax.swing.JComboBox<>();
        mailSignUp = new javax.swing.JTextField();
        confirmpass = new javax.swing.JPasswordField();
        pass_signup = new javax.swing.JPasswordField();
        mailSignUp1 = new javax.swing.JTextField();
        suCP2 = new javax.swing.JLabel();
        signUpButton = new PanelRound();
        signupWB = new javax.swing.JLabel();
        suCP3 = new javax.swing.JLabel();
        ssignup1 = new javax.swing.JLabel();
        LoginWordInSignUp = new javax.swing.JLabel();
        gotoHome1 = new PanelRound();
        gotoHomeIcon1 = new javax.swing.JLabel();
        L_Sign_UP_bg = new javax.swing.JLabel();
        Loginbg = new javax.swing.JPanel();
        Login_t_bg = new PanelRound();
        LoginWord = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        underEmail = new javax.swing.JLabel();
        iconMail = new javax.swing.JLabel();
        underEmail1 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtmail = new javax.swing.JTextField();
        show = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        ssignup = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        forget = new javax.swing.JLabel();
        LoginButton = new PanelRound();
        LoginWB = new javax.swing.JLabel();
        gotoHome = new PanelRound();
        gotoHomeIcon = new javax.swing.JLabel();
        LoginBackGround = new javax.swing.JLabel();
        forgetpassPanelParent = new javax.swing.JPanel();
        forgetPassPanel = new PanelRound();
        ResetPass_WB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        forgetButton = new PanelRound();
        forgetWB = new javax.swing.JLabel();
        signUpFromForget = new PanelRound();
        signUpWB_IN_Forget = new javax.swing.JLabel();
        loginFromForget = new PanelRound();
        LoginWB_IN_Forget = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        gender.add(female);
        gender.add(male);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("Login"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(102, 0, 0));
        closeButton.setRoundBottomLeft(15);
        closeButton.setRoundBottomRight(15);
        closeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeSymbol.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        closeSymbol.setForeground(new java.awt.Color(255, 255, 255));
        closeSymbol.setText("X");
        closeSymbol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeSymbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeSymbolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeSymbolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeSymbolMouseExited(evt);
            }
        });
        closeButton.add(closeSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 40, 30));

        setSize(975, 435);
        SignUPbg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpRoundPanel.setBackground(new java.awt.Color(8, 87, 158,40));
        SignUpRoundPanel.setRoundBottomLeft(150);
        SignUpRoundPanel.setRoundBottomRight(150);
        SignUpRoundPanel.setRoundTopLeft(150);
        SignUpRoundPanel.setRoundTopRight(150);
        SignUpRoundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUp_w.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        signUp_w.setForeground(new java.awt.Color(255, 255, 255));
        signUp_w.setText("Sign Up");
        signUp_w.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUpRoundPanel.add(signUp_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 190, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        SignUpRoundPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        SignUpRoundPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        suP.setForeground(new java.awt.Color(255, 255, 255));
        suP.setText("______________________________");
        SignUpRoundPanel.add(suP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Confirm PassWord");
        SignUpRoundPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        suE.setForeground(new java.awt.Color(255, 255, 255));
        suE.setText("______________________________");
        SignUpRoundPanel.add(suE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Username");
        SignUpRoundPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("+20");
        SignUpRoundPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 60, 60));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Governorate");
        SignUpRoundPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, 40));

        female.setBackground(new java.awt.Color(255, 102, 0));
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        SignUpRoundPanel.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        male.setBackground(new java.awt.Color(255, 102, 0));
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        SignUpRoundPanel.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Phone");
        SignUpRoundPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        Egypt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Egypt.setText("   Egypt");
        Egypt.setBorder(null);
        Egypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EgyptActionPerformed(evt);
            }
        });
        SignUpRoundPanel.add(Egypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 210, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Country");
        SignUpRoundPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        governorate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alexandria", "Aswan", "Assiut", "Beheira", "Beni Suef", "Cairo", "Dakahlia", "Damietta", "Fayoum", "Gharbia", "Giza", "Ismailia", "Kafr el-Sheikh", "Matrouh", "Minya", "Menofia", "New Valley", "North Sinai", "Port Said", "Qualyubia", "Qena", "Red Sea", "Al-Sharqia", "Sohaj", "South Sinai", "Suez", "Luxor", " " }));
        SignUpRoundPanel.add(governorate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 210, 40));

        mailSignUp.setBackground(new java.awt.Color(0,0,0,0));
        mailSignUp.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        mailSignUp.setForeground(new java.awt.Color(255, 255, 255));
        mailSignUp.setBorder(null);
        mailSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailSignUpActionPerformed(evt);
            }
        });
        SignUpRoundPanel.add(mailSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 210, 40));

        confirmpass.setBackground(new java.awt.Color(0,0,0,0));
        confirmpass.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        confirmpass.setForeground(new java.awt.Color(255, 255, 255));
        confirmpass.setBorder(null);
        confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassActionPerformed(evt);
            }
        });
        SignUpRoundPanel.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 40));

        pass_signup.setBackground(new java.awt.Color(0,0,0,0));
        pass_signup.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        pass_signup.setForeground(new java.awt.Color(255, 255, 255));
        pass_signup.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pass_signup.setBorder(null);
        pass_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pass_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_signupActionPerformed(evt);
            }
        });
        SignUpRoundPanel.add(pass_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 40));

        mailSignUp1.setBackground(new java.awt.Color(0,0,0,0));
        mailSignUp1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        mailSignUp1.setForeground(new java.awt.Color(255, 255, 255));
        mailSignUp1.setBorder(null);
        mailSignUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailSignUp1ActionPerformed(evt);
            }
        });
        SignUpRoundPanel.add(mailSignUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 40));

        suCP2.setForeground(new java.awt.Color(255, 255, 255));
        suCP2.setText("____________________________");
        SignUpRoundPanel.add(suCP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 30));

        signUpButton.setBackground(new java.awt.Color(255, 255, 255));
        signUpButton.setRoundTopLeft(40);
        signUpButton.setRoundTopRight(40);
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpButtonMouseExited(evt);
            }
        });
        signUpButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupWB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        signupWB.setForeground(new java.awt.Color(11, 65, 101));
        signupWB.setText("Sign UP");
        signupWB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupWB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupWBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupWBMouseExited(evt);
            }
        });
        signUpButton.add(signupWB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        SignUpRoundPanel.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 350, 50));

        suCP3.setForeground(new java.awt.Color(255, 255, 255));
        suCP3.setText("______________________________");
        SignUpRoundPanel.add(suCP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 30));

        ssignup1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ssignup1.setForeground(new java.awt.Color(255, 255, 255));
        ssignup1.setText("Already have an account!");
        SignUpRoundPanel.add(ssignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 160, -1));

        LoginWordInSignUp.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LoginWordInSignUp.setForeground(new java.awt.Color(18, 108, 161));
        LoginWordInSignUp.setText("Login");
        LoginWordInSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginWordInSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginWordInSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginWordInSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginWordInSignUpMouseExited(evt);
            }
        });
        SignUpRoundPanel.add(LoginWordInSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 60, -1));

        gotoHome1.setBackground(new java.awt.Color(255, 255, 255));
        gotoHome1.setRoundBottomLeft(150);
        gotoHome1.setRoundTopRight(150);
        gotoHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gotoHomeIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gotoHomeIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-26.png"))); // NOI18N
        gotoHomeIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gotoHomeIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    gotoHomeIcon1MouseClicked(evt);
                } catch (IOException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gotoHomeIcon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gotoHomeIcon1MouseExited(evt);
            }
        });
        gotoHome1.add(gotoHomeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 110));

        SignUpRoundPanel.add(gotoHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 100, 110));

        SignUPbg.add(SignUpRoundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 940, 380));

        L_Sign_UP_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sign up.png"))); // NOI18N
        SignUPbg.add(L_Sign_UP_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 975, 470));

        getContentPane().add(SignUPbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 440));

        Loginbg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_t_bg.setBackground(new java.awt.Color(8, 87, 158,40));
        Login_t_bg.setRoundBottomRight(150);
        Login_t_bg.setRoundTopRight(150);
        Login_t_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginWord.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        LoginWord.setForeground(new java.awt.Color(255, 255, 255));
        LoginWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginWord.setText("Login");
        LoginWord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login_t_bg.add(LoginWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 5, 300, 60));

        pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password");
        Login_t_bg.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Username");
        Login_t_bg.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        underEmail.setForeground(new java.awt.Color(255, 255, 255));
        underEmail.setText("__________________________________________________");
        underEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        underEmail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Login_t_bg.add(underEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 400, 20));
        underEmail.getAccessibleContext().setAccessibleDescription("");

        iconMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-gmail-logo-30.png"))); // NOI18N
        Login_t_bg.add(iconMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 30, 20));

        underEmail1.setForeground(new java.awt.Color(255, 255, 255));
        underEmail1.setText("__________________________________________________");
        underEmail1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        underEmail1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Login_t_bg.add(underEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 400, 20));

        txtpass.setFont(txtpass.getFont().deriveFont(txtpass.getFont().getSize()+2f));
        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setBorder(null);
        txtpass.setCaretColor(new java.awt.Color(255, 255, 255));
        Login_t_bg.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, 320, 40));

        txtmail.setFont(txtmail.getFont().deriveFont(txtmail.getFont().getSize()+2f));
        txtmail.setForeground(new java.awt.Color(255, 255, 255));
        txtmail.setBorder(null);
        txtmail.setCaretColor(new java.awt.Color(255, 255, 255));
        Login_t_bg.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 320, 40));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-unlock-30.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        Login_t_bg.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 30, 30));

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-lock-30.png"))); // NOI18N
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        Login_t_bg.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 30, 30));

        signup.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(18, 108, 161));
        signup.setText("SIGN UP");
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });
        Login_t_bg.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        ssignup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ssignup.setForeground(new java.awt.Color(255, 255, 255));
        ssignup.setText("Don't have an account?");
        Login_t_bg.add(ssignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Remember Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Login_t_bg.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        forget.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forget.setForeground(new java.awt.Color(18, 108, 161));
        forget.setText("Forget Password?");
        forget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgetMouseExited(evt);
            }
        });
        Login_t_bg.add(forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setRoundBottomLeft(40);
        LoginButton.setRoundBottomRight(40);
        LoginButton.setRoundTopLeft(40);
        LoginButton.setRoundTopRight(40);
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    LoginButtonMouseClicked(evt);
                } catch (IOException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });
        LoginButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginWB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginWB.setForeground(new java.awt.Color(11, 65, 101));
        LoginWB.setText("LOGIN");
        LoginWB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginWB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginWBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginWBMouseExited(evt);
            }
        });
        LoginButton.add(LoginWB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        Login_t_bg.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, 50));

        gotoHome.setBackground(new java.awt.Color(255, 255, 255));
        gotoHome.setRoundBottomLeft(150);
        gotoHome.setRoundTopRight(150);
        gotoHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gotoHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gotoHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-26.png"))); // NOI18N
        gotoHomeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gotoHomeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    gotoHomeIconMouseClicked(evt);
                } catch (IOException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gotoHomeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gotoHomeIconMouseExited(evt);
            }
        });
        gotoHome.add(gotoHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 110));

        Login_t_bg.add(gotoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 100, 110));

        Loginbg.add(Login_t_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 510, 400));

        LoginBackGround.setForeground(new java.awt.Color(224, 237, 242));
        LoginBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login_final.png"))); // NOI18N
        Loginbg.add(LoginBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Loginbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        forgetpassPanelParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgetPassPanel.setBackground(new java.awt.Color(8, 87, 158,40));
        forgetPassPanel.setRoundBottomRight(150);
        forgetPassPanel.setRoundTopRight(150);
        forgetPassPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResetPass_WB.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        ResetPass_WB.setForeground(new java.awt.Color(255, 255, 255));
        ResetPass_WB.setText("Reset Password");
        forgetPassPanel.add(ResetPass_WB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 410, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Your Email");
        forgetPassPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("_________________________________________________________");
        forgetPassPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTextField1.setBackground(new java.awt.Color(0,0,0,0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        forgetPassPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 280, 40));

        forgetButton.setBackground(new java.awt.Color(255, 255, 255));
        forgetButton.setRoundBottomLeft(40);
        forgetButton.setRoundBottomRight(40);
        forgetButton.setRoundTopLeft(40);
        forgetButton.setRoundTopRight(40);
        forgetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgetButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgetButtonMouseExited(evt);
            }
        });
        forgetButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgetWB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        forgetWB.setForeground(new java.awt.Color(11, 65, 101));
        forgetWB.setText("Send Password To Email");
        forgetWB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetWB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgetWBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgetWBMouseExited(evt);
            }
        });
        forgetButton.add(forgetWB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        forgetPassPanel.add(forgetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 360, 50));

        signUpFromForget.setBackground(new java.awt.Color(51, 68, 78));
        signUpFromForget.setRoundTopLeft(50);
        signUpFromForget.setRoundTopRight(50);
        signUpFromForget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpFromForgetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpFromForgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpFromForgetMouseExited(evt);
            }
        });
        signUpFromForget.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpWB_IN_Forget.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        signUpWB_IN_Forget.setForeground(new java.awt.Color(255, 255, 255));
        signUpWB_IN_Forget.setText("Sign Up");
        signUpWB_IN_Forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpWB_IN_ForgetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpWB_IN_ForgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpWB_IN_ForgetMouseExited(evt);
            }
        });
        signUpFromForget.add(signUpWB_IN_Forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        forgetPassPanel.add(signUpFromForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 120, 40));
        signUpFromForget.getAccessibleContext().setAccessibleName("");

        loginFromForget.setBackground(new java.awt.Color(51, 68, 78));
        loginFromForget.setForeground(new java.awt.Color(255, 255, 255));
        loginFromForget.setRoundTopLeft(50);
        loginFromForget.setRoundTopRight(50);
        loginFromForget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginFromForgetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginFromForgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginFromForgetMouseExited(evt);
            }
        });
        loginFromForget.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginWB_IN_Forget.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        LoginWB_IN_Forget.setForeground(new java.awt.Color(255, 255, 255));
        LoginWB_IN_Forget.setText("Login");
        LoginWB_IN_Forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginWB_IN_ForgetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginWB_IN_ForgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginWB_IN_ForgetMouseExited(evt);
            }
        });
        loginFromForget.add(LoginWB_IN_Forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        forgetPassPanel.add(loginFromForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, 40));

        forgetpassPanelParent.add(forgetPassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 510, 400));
        forgetPassPanel.getAccessibleContext().setAccessibleParent(forgetpassPanelParent);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login_final.png"))); // NOI18N
        forgetpassPanelParent.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(forgetpassPanelParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 440));

        setSize(new java.awt.Dimension(975, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeSymbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSymbolMouseClicked
        dispose();
    }//GEN-LAST:event_closeSymbolMouseClicked

    private void closeSymbolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSymbolMouseEntered
        closeButton.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_closeSymbolMouseEntered

    private void closeSymbolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeSymbolMouseExited
        closeButton.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_closeSymbolMouseExited

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void LoginWBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginWBMouseEntered
        LoginButton.setBackground(new Color(46, 144, 232));
        LoginWB.setForeground(Color.white);
    }//GEN-LAST:event_LoginWBMouseEntered

    private void LoginWBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginWBMouseExited
        LoginButton.setBackground(new Color(255, 255, 255));
        LoginWB.setForeground(new Color(11, 65, 101));
    }//GEN-LAST:event_LoginWBMouseExited

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered

        LoginButton.setBackground(new Color(46, 144, 232));
        LoginWB.setForeground(Color.white);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        LoginButton.setBackground(new Color(255, 255, 255));
        LoginWB.setForeground(new Color(11, 65, 101));
        setCursor(NORMAL);
    }//GEN-LAST:event_LoginButtonMouseExited

    private void forgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseEntered
        forget.setForeground(new Color(209, 49, 26));
    }//GEN-LAST:event_forgetMouseEntered

    private void forgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseExited
        forget.setForeground(new Color(18, 108, 161));
    }//GEN-LAST:event_forgetMouseExited

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
        signup.setForeground(new Color(209, 49, 26));
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
        signup.setForeground(new Color(18, 108, 161));
    }//GEN-LAST:event_signupMouseExited

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        txtpass.setEchoChar((char) 0);
        hide.setVisible(false);
        hide.setEnabled(false);
        show.setVisible(true);
        show.setEnabled(true);
    }//GEN-LAST:event_hideMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        txtpass.setEchoChar((char) 8226);
        hide.setVisible(true);
        hide.setEnabled(true);
        show.setVisible(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.2) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_LoginButtonMouseClicked
        String username = txtmail.getText();
        String password = txtpass.getText();
        if (password.equals("") || username.equals("")) {
            JOptionPane.showMessageDialog(this, "Empty UserName or Password");
        }
        else {
            MainFram m = new MainFram(username, password, jCheckBox1.isSelected());
            m.show();
            this.dispose();
            
        }
        
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        SignUpFrame su = new SignUpFrame();
        su.show();
        this.dispose();

    }//GEN-LAST:event_signupMouseClicked

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void EgyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EgyptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EgyptActionPerformed

    private void mailSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailSignUpActionPerformed

    private void mailSignUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailSignUp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailSignUp1ActionPerformed

    private void signupWBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupWBMouseEntered
        signUpButton.setBackground(new Color(46, 144, 232));
        signupWB.setForeground(Color.white);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_signupWBMouseEntered

    private void signupWBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupWBMouseExited
        signUpButton.setBackground(new Color(255, 255, 255));
        signupWB.setForeground(new Color(11, 65, 101));
        setCursor(NORMAL);
    }//GEN-LAST:event_signupWBMouseExited

    private void signUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonMouseClicked

    private void signUpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseEntered
        signUpButton.setBackground(new Color(46, 144, 232));
        signupWB.setForeground(Color.white);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_signUpButtonMouseEntered

    private void signUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseExited
        signUpButton.setBackground(new Color(255, 255, 255));
        signupWB.setForeground(new Color(11, 65, 101));
        setCursor(NORMAL);
    }//GEN-LAST:event_signUpButtonMouseExited

    private void pass_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_signupActionPerformed

    private void confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassActionPerformed

    private void LoginWordInSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginWordInSignUpMouseClicked
        Loginbg.setVisible(true);
        SignUPbg.setVisible(false);
    }//GEN-LAST:event_LoginWordInSignUpMouseClicked

    private void LoginWordInSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginWordInSignUpMouseEntered
        LoginWordInSignUp.setForeground(new Color(209, 49, 26));
    }//GEN-LAST:event_LoginWordInSignUpMouseEntered

    private void LoginWordInSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginWordInSignUpMouseExited
        LoginWordInSignUp.setForeground(new Color(18, 108, 161));
    }//GEN-LAST:event_LoginWordInSignUpMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void forgetWBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetWBMouseEntered
        forgetButton.setBackground(new Color(46, 144, 232));
        forgetWB.setForeground(Color.white);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_forgetWBMouseEntered

    private void forgetWBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetWBMouseExited
        forgetButton.setBackground(new Color(255, 255, 255));
        forgetWB.setForeground(new Color(11, 65, 101));
        setCursor(NORMAL);
    }//GEN-LAST:event_forgetWBMouseExited

    private void forgetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_forgetButtonMouseClicked

    private void forgetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetButtonMouseEntered
        forgetButton.setBackground(new Color(46, 144, 232));
        forgetWB.setForeground(Color.white);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_forgetButtonMouseEntered

    private void forgetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetButtonMouseExited
        forgetButton.setBackground(new Color(255, 255, 255));
        forgetWB.setForeground(new Color(11, 65, 101));
        setCursor(NORMAL);
    }//GEN-LAST:event_forgetButtonMouseExited

    private void loginFromForgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFromForgetMouseEntered
        loginFromForget.setBackground(new Color(30, 123, 194));
        LoginWB_IN_Forget.setForeground(Color.BLACK);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_loginFromForgetMouseEntered

    private void LoginWB_IN_ForgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginWB_IN_ForgetMouseExited
        loginFromForget.setBackground(new Color(51, 68, 78));
        LoginWB_IN_Forget.setForeground(new Color(225, 225, 225));
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_LoginWB_IN_ForgetMouseExited

    private void LoginWB_IN_ForgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginWB_IN_ForgetMouseEntered
        loginFromForget.setBackground(new Color(30, 123, 194));
        LoginWB_IN_Forget.setForeground(Color.BLACK);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_LoginWB_IN_ForgetMouseEntered

    private void loginFromForgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFromForgetMouseExited
        loginFromForget.setBackground(new Color(51, 68, 78));
        LoginWB_IN_Forget.setForeground(new Color(225, 225, 225));
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_loginFromForgetMouseExited

    private void LoginWB_IN_ForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginWB_IN_ForgetMouseClicked
        forgetPassPanel.setVisible(false);
        Loginbg.setVisible(true);
    }//GEN-LAST:event_LoginWB_IN_ForgetMouseClicked

    private void loginFromForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFromForgetMouseClicked
        forgetPassPanel.setVisible(false);
        Loginbg.setVisible(true);
    }//GEN-LAST:event_loginFromForgetMouseClicked

    private void forgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseClicked
        forgetPassPanel.setVisible(true);
        Loginbg.setVisible(false);
        forgetpassPanelParent.setVisible(true);
    }//GEN-LAST:event_forgetMouseClicked

    private void signUpFromForgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpFromForgetMouseEntered
        signUpFromForget.setBackground(new Color(30, 123, 194));
        signUpWB_IN_Forget.setForeground(Color.BLACK);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_signUpFromForgetMouseEntered

    private void signUpWB_IN_ForgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpWB_IN_ForgetMouseEntered
        signUpFromForget.setBackground(new Color(30, 123, 194));
        signUpWB_IN_Forget.setForeground(Color.BLACK);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_signUpWB_IN_ForgetMouseEntered

    private void signUpWB_IN_ForgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpWB_IN_ForgetMouseExited
        signUpFromForget.setBackground(new Color(51, 68, 78));
        signUpWB_IN_Forget.setForeground(Color.WHITE);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_signUpWB_IN_ForgetMouseExited

    private void signUpFromForgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpFromForgetMouseExited
        signUpFromForget.setBackground(new Color(51, 68, 78));
        signUpWB_IN_Forget.setForeground(Color.WHITE);
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_signUpFromForgetMouseExited

    private void signUpWB_IN_ForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpWB_IN_ForgetMouseClicked
        forgetpassPanelParent.setVisible(false);
        SignUPbg.setVisible(true);
    }//GEN-LAST:event_signUpWB_IN_ForgetMouseClicked

    private void signUpFromForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpFromForgetMouseClicked
        forgetpassPanelParent.setVisible(false);
        SignUPbg.setVisible(true);
    }//GEN-LAST:event_signUpFromForgetMouseClicked

    private void gotoHomeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoHomeIconMouseEntered
        gotoHome.setBackground(new Color(46, 144, 232));
    }//GEN-LAST:event_gotoHomeIconMouseEntered

    private void gotoHomeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoHomeIconMouseExited
        gotoHome.setBackground(Color.WHITE);
    }//GEN-LAST:event_gotoHomeIconMouseExited

    private void gotoHomeIconMouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_gotoHomeIconMouseClicked
        MainFram FF = new MainFram();
        FF.show();
        this.dispose();
    }//GEN-LAST:event_gotoHomeIconMouseClicked

    private void gotoHomeIcon1MouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_gotoHomeIcon1MouseClicked
        MainFram FF = new MainFram();
        FF.show();
        this.dispose();
    }//GEN-LAST:event_gotoHomeIcon1MouseClicked

    private void gotoHomeIcon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoHomeIcon1MouseEntered
        gotoHome1.setBackground(new Color(46, 144, 232));
    }//GEN-LAST:event_gotoHomeIcon1MouseEntered

    private void gotoHomeIcon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoHomeIcon1MouseExited
        gotoHome1.setBackground(Color.WHITE);
    }//GEN-LAST:event_gotoHomeIcon1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Egypt;
    private javax.swing.JLabel L_Sign_UP_bg;
    private javax.swing.JLabel LoginBackGround;
    private PanelRound LoginButton;
    private javax.swing.JLabel LoginWB;
    private javax.swing.JLabel LoginWB_IN_Forget;
    private javax.swing.JLabel LoginWord;
    private javax.swing.JLabel LoginWordInSignUp;
    private PanelRound Login_t_bg;
    private javax.swing.JPanel Loginbg;
    private javax.swing.JLabel ResetPass_WB;
    private javax.swing.JPanel SignUPbg;
    private PanelRound SignUpRoundPanel;
    private PanelRound closeButton;
    private javax.swing.JLabel closeSymbol;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JLabel email;
    private RadioButtonCustom female;
    private javax.swing.JLabel forget;
    private PanelRound forgetButton;
    private PanelRound forgetPassPanel;
    private javax.swing.JLabel forgetWB;
    private javax.swing.JPanel forgetpassPanelParent;
    private javax.swing.ButtonGroup gender;
    private PanelRound gotoHome;
    private PanelRound gotoHome1;
    private javax.swing.JLabel gotoHomeIcon;
    private javax.swing.JLabel gotoHomeIcon1;
    private javax.swing.JComboBox<String> governorate;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel iconMail;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private PanelRound loginFromForget;
    private javax.swing.JTextField mailSignUp;
    private javax.swing.JTextField mailSignUp1;
    private RadioButtonCustom male;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField pass_signup;
    private javax.swing.JLabel show;
    private PanelRound signUpButton;
    private PanelRound signUpFromForget;
    private javax.swing.JLabel signUpWB_IN_Forget;
    private javax.swing.JLabel signUp_w;
    private javax.swing.JLabel signup;
    private javax.swing.JLabel signupWB;
    private javax.swing.JLabel ssignup;
    private javax.swing.JLabel ssignup1;
    private javax.swing.JLabel suCP2;
    private javax.swing.JLabel suCP3;
    private javax.swing.JLabel suE;
    private javax.swing.JLabel suP;
    private javax.swing.JTextField txtmail;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JLabel underEmail;
    private javax.swing.JLabel underEmail1;
    // End of variables declaration//GEN-END:variables
class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
